server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/springtestdb?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.doudou.springcloud.entities

eureka:
  client:
    register-with-eureka: true  # 表示是否将自己注入当EurekaServer中，默认为true
    fetch-registry: true  # 表示是否从EurekaServer中抓取已注册的信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://myeureka7001.com:7001/eureka/,http://myeureka7002.com:7002/eureka/
  instance:
    instance-id: payment8001
    prefer-ip-address: true